<?php

namespace Nesk\Puphpeteer\Resources;

use Nesk\Puphpeteer\Traits\AliasesEvaluationMethods;
use Nesk\Puphpeteer\Traits\AliasesSelectionMethods;

/**
 * @property-read \Nesk\Puphpeteer\Resources\Keyboard $keyboard
 * @property-read \Nesk\Puphpeteer\Resources\Touchscreen $touchscreen
 * @property-read \Nesk\Puphpeteer\Resources\Coverage $coverage
 * @property-read \Nesk\Puphpeteer\Resources\Tracing $tracing
 * @property-read \Nesk\Puphpeteer\Resources\Accessibility $accessibility
 * @property-read \Nesk\Puphpeteer\Resources\Mouse $mouse
 * @method bool isServiceWorkerBypassed()
 * @method-extended bool isServiceWorkerBypassed()
 * @method bool isDragInterceptionEnabled()
 * @method-extended bool isDragInterceptionEnabled()
 * @method bool isJavaScriptEnabled()
 * @method-extended bool isJavaScriptEnabled()
 * @method mixed on(mixed $type, \Nesk\Rialto\Data\JsFunction $handler)
 * @method-extended mixed on(mixed $type, callable(mixed $event): void|\Nesk\Rialto\Data\JsFunction $handler)
 * @method mixed off(mixed $type, \Nesk\Rialto\Data\JsFunction $handler)
 * @method-extended mixed off(mixed $type, callable(mixed $event): void|\Nesk\Rialto\Data\JsFunction $handler)
 * @method \Nesk\Puphpeteer\Resources\FileChooser waitForFileChooser(array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\FileChooser waitForFileChooser(array<string, mixed> $options = null)
 * @method void setGeolocation(array $options)
 * @method-extended void setGeolocation(array<string, mixed> $options)
 * @method \Nesk\Puphpeteer\Resources\Target target()
 * @method-extended \Nesk\Puphpeteer\Resources\Target target()
 * @method \Nesk\Puphpeteer\Resources\Browser browser()
 * @method-extended \Nesk\Puphpeteer\Resources\Browser browser()
 * @method \Nesk\Puphpeteer\Resources\BrowserContext browserContext()
 * @method-extended \Nesk\Puphpeteer\Resources\BrowserContext browserContext()
 * @method \Nesk\Puphpeteer\Resources\Frame mainFrame()
 * @method-extended \Nesk\Puphpeteer\Resources\Frame mainFrame()
 * @method \Nesk\Puphpeteer\Resources\CDPSession createCDPSession()
 * @method-extended \Nesk\Puphpeteer\Resources\CDPSession createCDPSession()
 * @method \Nesk\Puphpeteer\Resources\Frame[] frames()
 * @method-extended \Nesk\Puphpeteer\Resources\Frame[] frames()
 * @method \Nesk\Puphpeteer\Resources\WebWorker[] workers()
 * @method-extended \Nesk\Puphpeteer\Resources\WebWorker[] workers()
 * @method void setRequestInterception(bool $value)
 * @method-extended void setRequestInterception(bool $value)
 * @method void setBypassServiceWorker(bool $bypass)
 * @method-extended void setBypassServiceWorker(bool $bypass)
 * @method void setDragInterception(bool $enabled)
 * @method-extended void setDragInterception(bool $enabled)
 * @method void setOfflineMode(bool $enabled)
 * @method-extended void setOfflineMode(bool $enabled)
 * @method void emulateNetworkConditions(mixed|null $networkConditions)
 * @method-extended void emulateNetworkConditions(mixed|null $networkConditions)
 * @method void setDefaultNavigationTimeout(float $timeout)
 * @method-extended void setDefaultNavigationTimeout(float $timeout)
 * @method void setDefaultTimeout(float $timeout)
 * @method-extended void setDefaultTimeout(float $timeout)
 * @method float getDefaultTimeout()
 * @method-extended float getDefaultTimeout()
 * @method mixed locator(\Nesk\Rialto\Data\JsFunction $func)
 * @method-extended mixed locator(callable(): mixed|\Nesk\Rialto\Data\JsFunction $func)
 * @method mixed locatorRace(mixed $locators)
 * @method-extended mixed locatorRace(mixed $locators)
 * @method mixed evaluateHandle(\Nesk\Rialto\Data\JsFunction $pageFunction, mixed ...$args)
 * @method-extended mixed evaluateHandle(callable|\Nesk\Rialto\Data\JsFunction $pageFunction, mixed ...$args)
 * @method \Nesk\Puphpeteer\Resources\JSHandle|mixed[][] queryObjects(\Nesk\Puphpeteer\Resources\JSHandle|mixed[] $prototypeHandle)
 * @method-extended \Nesk\Puphpeteer\Resources\JSHandle|mixed[][] queryObjects(\Nesk\Puphpeteer\Resources\JSHandle|mixed[] $prototypeHandle)
 * @method mixed[] cookies(string ...$urls)
 * @method-extended mixed[] cookies(string ...$urls)
 * @method void deleteCookie(mixed ...$cookies)
 * @method-extended void deleteCookie(mixed ...$cookies)
 * @method void setCookie(mixed ...$cookies)
 * @method-extended void setCookie(mixed ...$cookies)
 * @method \Nesk\Puphpeteer\Resources\ElementHandle|mixed[] addScriptTag(array $options)
 * @method-extended \Nesk\Puphpeteer\Resources\ElementHandle|mixed[] addScriptTag(array<string, mixed> $options)
 * @method \Nesk\Puphpeteer\Resources\ElementHandle|mixed[] addStyleTag(array $options)
 * @method-extended \Nesk\Puphpeteer\Resources\ElementHandle|mixed[] addStyleTag(array<string, mixed> $options)
 * @method void exposeFunction(string $name, \Nesk\Rialto\Data\JsFunction|array $pptrFunction)
 * @method-extended void exposeFunction(string $name, callable|\Nesk\Rialto\Data\JsFunction|array{ $default: callable|\Nesk\Rialto\Data\JsFunction } $pptrFunction)
 * @method void removeExposedFunction(string $name)
 * @method-extended void removeExposedFunction(string $name)
 * @method void authenticate(mixed|null $credentials)
 * @method-extended void authenticate(mixed|null $credentials)
 * @method void setExtraHTTPHeaders(array|string[]|string[] $headers)
 * @method-extended void setExtraHTTPHeaders(array|string[]|string[] $headers)
 * @method void setUserAgent(string $userAgent, mixed $userAgentMetadata = null)
 * @method-extended void setUserAgent(string $userAgent, mixed $userAgentMetadata = null)
 * @method mixed metrics()
 * @method-extended mixed metrics()
 * @method string url()
 * @method-extended string url()
 * @method string content()
 * @method-extended string content()
 * @method void setContent(string $html, array $options = [])
 * @method-extended void setContent(string $html, array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPResponse|null goto(string $url, array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPResponse|null goto(string $url, array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPResponse|null reload(array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPResponse|null reload(array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPResponse|null waitForNavigation(array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPResponse|null waitForNavigation(array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPRequest waitForRequest(string|mixed $urlOrPredicate, array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPRequest waitForRequest(string|mixed $urlOrPredicate, array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPResponse waitForResponse(string|mixed $urlOrPredicate, array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPResponse waitForResponse(string|mixed $urlOrPredicate, array<string, mixed> $options = null)
 * @method void waitForNetworkIdle(array $options = [])
 * @method-extended void waitForNetworkIdle(array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\Frame waitForFrame(string|\Nesk\Rialto\Data\JsFunction $urlOrPredicate, array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\Frame waitForFrame(string|callable(callable(\Nesk\Puphpeteer\Resources\Frame $frame): mixed|\Nesk\Rialto\Data\JsFunction): |\Nesk\Rialto\Data\JsFunction $urlOrPredicate, array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPResponse|null goBack(array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPResponse|null goBack(array<string, mixed> $options = null)
 * @method \Nesk\Puphpeteer\Resources\HTTPResponse|null goForward(array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\HTTPResponse|null goForward(array<string, mixed> $options = null)
 * @method void bringToFront()
 * @method-extended void bringToFront()
 * @method void emulate(mixed $device)
 * @method-extended void emulate(mixed $device)
 * @method void setJavaScriptEnabled(bool $enabled)
 * @method-extended void setJavaScriptEnabled(bool $enabled)
 * @method void setBypassCSP(bool $enabled)
 * @method-extended void setBypassCSP(bool $enabled)
 * @method void emulateMediaType(string $type = null)
 * @method-extended void emulateMediaType(string $type = null)
 * @method void emulateCPUThrottling(float|null $factor)
 * @method-extended void emulateCPUThrottling(float|null $factor)
 * @method void emulateMediaFeatures(mixed[] $features = null)
 * @method-extended void emulateMediaFeatures(mixed[] $features = null)
 * @method void emulateTimezone(string $timezoneId = null)
 * @method-extended void emulateTimezone(string $timezoneId = null)
 * @method void emulateIdleState(array $overrides = [])
 * @method-extended void emulateIdleState(array{ $isUserActive: bool, $isScreenUnlocked: bool } $overrides = null)
 * @method void emulateVisionDeficiency(mixed $type = null)
 * @method-extended void emulateVisionDeficiency(mixed $type = null)
 * @method void setViewport(mixed|null $viewport)
 * @method-extended void setViewport(mixed|null $viewport)
 * @method mixed|null viewport()
 * @method-extended mixed|null viewport()
 * @method mixed evaluate(\Nesk\Rialto\Data\JsFunction $pageFunction, mixed ...$args)
 * @method-extended mixed evaluate(callable|\Nesk\Rialto\Data\JsFunction $pageFunction, mixed ...$args)
 * @method mixed evaluateOnNewDocument(\Nesk\Rialto\Data\JsFunction $pageFunction, mixed ...$args)
 * @method-extended mixed evaluateOnNewDocument(callable|\Nesk\Rialto\Data\JsFunction $pageFunction, mixed ...$args)
 * @method void removeScriptToEvaluateOnNewDocument(string $identifier)
 * @method-extended void removeScriptToEvaluateOnNewDocument(string $identifier)
 * @method void setCacheEnabled(bool $enabled = null)
 * @method-extended void setCacheEnabled(bool $enabled = null)
 * @method \Nesk\Puphpeteer\Resources\ScreenRecorder screencast(mixed $options = null)
 * @method-extended \Nesk\Puphpeteer\Resources\ScreenRecorder screencast(mixed $options = null)
 * @method mixed screenshot(mixed $options = null)
 * @method-extended mixed screenshot(mixed $options = null)
 * @method mixed createPDFStream(array $options = [])
 * @method-extended mixed createPDFStream(array<string, mixed> $options = null)
 * @method mixed pdf(array $options = [])
 * @method-extended mixed pdf(array<string, mixed> $options = null)
 * @method string title()
 * @method-extended string title()
 * @method void close(array $options = [])
 * @method-extended void close(array{ $runBeforeUnload: bool } $options = null)
 * @method bool isClosed()
 * @method-extended bool isClosed()
 * @method void click(string $selector, mixed $options = null)
 * @method-extended void click(string $selector, mixed $options = null)
 * @method void focus(string $selector)
 * @method-extended void focus(string $selector)
 * @method void hover(string $selector)
 * @method-extended void hover(string $selector)
 * @method string[] select(string $selector, string ...$values)
 * @method-extended string[] select(string $selector, string ...$values)
 * @method void tap(string $selector)
 * @method-extended void tap(string $selector)
 * @method void type(string $selector, string $text, mixed $options = null)
 * @method-extended void type(string $selector, string $text, mixed $options = null)
 * @method \Nesk\Puphpeteer\Resources\ElementHandle|mixed[]|null waitForSelector(mixed $selector, array $options = [])
 * @method-extended \Nesk\Puphpeteer\Resources\ElementHandle|mixed[]|null waitForSelector(mixed $selector, array<string, mixed> $options = null)
 * @method mixed waitForFunction(\Nesk\Rialto\Data\JsFunction $pageFunction, array $options = [], mixed ...$args)
 * @method-extended mixed waitForFunction(callable|\Nesk\Rialto\Data\JsFunction $pageFunction, array<string, mixed> $options = null, mixed ...$args)
 * @method mixed waitForDevicePrompt(array $options = [])
 * @method-extended mixed waitForDevicePrompt(array<string, mixed> $options = null)
 */
class Page extends EventEmitter
{
    use AliasesEvaluationMethods;
    use AliasesSelectionMethods;
}
